<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Payroll extends Model
{
    use HasFactory;

    protected $fillable = [
        'employee_id',
        'month',
        'year',
        'basic_salary',
        'shift_allowance',
        'incentives',
        'overtime_hours',
        'overtime_payment',
        'present_days',
        'half_days',
        'absent_days',
        'leave_days',
        'paid_leave_days',
        'unpaid_leave_days',
        'gross_salary',
        'pf_deduction',
        'mess_deduction',
        'other_deduction',
        'leave_deduction',
        'penalty_deduction',
        'net_salary',
        'status',
        'generated_by',
    ];

    protected $casts = [
        'basic_salary'       => 'decimal:2',
        'shift_allowance'    => 'decimal:2',
        'incentives'         => 'decimal:2',
        'overtime_hours'     => 'decimal:2',
        'overtime_payment'   => 'decimal:2',
        'gross_salary'       => 'decimal:2',
        'pf_deduction'       => 'decimal:2',
        'mess_deduction'     => 'decimal:2',
        'other_deduction'    => 'decimal:2',
        'leave_deduction'    => 'decimal:2',
        'penalty_deduction'  => 'decimal:2',
        'net_salary'         => 'decimal:2',
        'month'              => 'integer',
        'year'               => 'integer',
        'present_days'       => 'integer',
        'half_days'          => 'integer',
        'absent_days'        => 'integer',
        'leave_days'         => 'integer',
        'paid_leave_days'    => 'integer',
        'unpaid_leave_days'  => 'integer',
    ];

    /**
     * Relationship: Payroll belongs to an Employee
     */
    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    /**
     * Relationship: Payroll was generated by a User
     */
    public function generatedBy()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }

    /**
     * Relationship: Payroll has many PayrollItems
     */
    public function items()
    {
        return $this->hasMany(PayrollItem::class);
    }
}
